spring:
    config:
        activate:
            on-profile: docker
    cloud:
      kubernetes:
        enabled: false

name: Docker
enabled: true

server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
---
spring:
    config:
        activate:
            on-profile: kubernetes
name: Kubernetes
enabled: false
