server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
      - TokenRelay
      routes:
        - id: guest-service
          uri: lb://guest-service
          predicates:
            - Path=/guests/**
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/reservations/**
        - id: room-service
          uri: lb://room-service
          predicates:
            - Path=/rooms/**
        - id: room-reservation-service
          uri: lb://room-reservation-service
          predicates:
            - Path=/room-reservations/**
  security:
    oauth2:
      client:
        provider:
          keycloack:
            issuer-uri: http://localhost:8180/auth/realms/spring-cloud-gateway-realm
            user-name-attribute: preferred_username
        registration:
          gateway:
            provider: keycloack
            client-id: spring-cloud-gateway-client
            client-secret: 4ac9fb73-4cdc-4c3d-b35a-faadbfdc07db
---
spring:
  profiles: docker
  zipkin:
    baseUrl: http://tracing-server:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
